version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: wird
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password


volumes:
  postgres_data: