version: '3.8'

services:
  wird_backend:
    image: wird_back:prod
    command: ./start-server.sh
    volumes:
      - /var/www/html/wird_app:/home/app/web/staticfiles
      - /var/www/html/wird_app:/home/app/web/mediafiles
    ports:
      - 8200:8000
    env_file:
      - backend_vars.env
    depends_on:
      - wird_db
      - wird_redis
    networks:
      - wird_network

  wird_db:
    image: postgres:13.0-alpine
    volumes:
      - wird_db_data:/var/lib/postgresql/data/
    env_file:
      - db_vars.env
    networks:
      - wird_network

  wird_redis:
    image: redis:7.0.2-alpine
    command: redis-server
    networks:
      - wird_network

volumes:
  wird_db_data:

networks:
  wird_network:
    driver: bridge