version: '3.8'

services:
  wird_back:
    build:
      context: ./Ramadan_Competition_Rest
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .wird_django_local.env
    depends_on:
      - db
    networks:
      - wird-network

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .wird_db_local.env
    networks:
      - wird-network

  redis:
    image: redis:7.0.2-alpine
    command: redis-server
    expose:
      - "6379"
    networks:
      - wird-network

volumes:
  postgres_data:

networks:
  wird-network:
    driver: bridge
